Here’s a simple example of a Continuous Integration (CI) pipeline configuration using GitHub Actions. This example runs tests for a Node.js project whenever code is pushed to the repository:

Copy code
name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

Key Points:
Trigger: The pipeline runs on push or pull_request events targeting the main branch.
Environment: It uses the latest Ubuntu runner.
Steps:
# Checks out the repository code.
# Sets up Node.js (version 16 in this case).
# Installs dependencies using npm install.
# Runs tests with npm test.

# This is a minimal example and can be adapted for other languages, frameworks, or tools. Let me know if you'd like a variation for a different tech stack!